### ISSUE TITLE
Should respect the `--no-color` option when run via pack

### ISSUE THREAD

**Issue by trisberg** [projectriff/libfnbuildpack#56]
Using `--no-color` flag or setting `color.NoColor = true` before running the build should suppress the colors from the log output. At the moment the riff builder part still omits colored log output while the rest of the output show no colors.

**Comment by trisberg** [comment]
This seems to be a general issue with pack and how buildpacks are invoked, see https://github.com/buildpack/pack/issues/123

**Comment by nebhale** [comment]
It's more likely because we [unconditionally set color as enabled](https://github.com/cloudfoundry/libcfbuildpack/blob/master/logger/logger.go#L36).  The problem is that buildpacks are invoked no-`tty` so color would never show.  If the `lifecycle` conditionally invoked the buildpacks with a `tty` normally and then without a `tty` when using `--no-color`, I'd relax that.
